
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
/*import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});*/

import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",

  migrations: {
    path: "prisma/migrations",
    seed: "tsx --tsconfig tsconfig.seed.json prisma/seed.ts",
  },

  engine: "classic",

  datasource: {
    url: env("DATABASE_URL"),
  },
});
